version: '2'
services:
 mydatabase:
  build:
   context: .
   dockerfile: dbDockerfile
  ports:
  - "3306"
  container_name: mydatabase
  environment:
  - "MYSQL_ROOT_PASSWORD=1234"
  - "MYSQL_DATABASE=my_presta_database"
  restart: always
 presta:
  build:
   context: .
   dockerfile: prestaDockerFile
  ports:
  - "8888:80"
  container_name: presta
  links:
  - "mydatabase"
  volumes:
  - "./website:/var/www/html"
  environment:
  - "DB_SERVER=mydatabase"
  - "DB_USER=root"
  - "DB_PASSWD=1234"
  - "DB_NAME=my_presta_database"
  restart: always
